apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rx-demo
  namespace: argocd
spec:
  description: NKP Rx demo project
  sourceRepos:
    - https://github.com/icediceice/Nutanix-Demo
    - https://github.com/icediceice/Nutanix-Demo.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
