apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: frontend
  namespace: demo-app
spec:
  http:
    - route:
        - destination:
            host: frontend.demo-app.svc.cluster.local
            subset: v1
          weight: 100
        - destination:
            host: frontend.demo-app.svc.cluster.local
            subset: v2
          weight: 0
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: frontend-ingress
  namespace: demo-app
spec:
  http:
    - route:
        - destination:
            host: frontend.demo-app.svc.cluster.local
            subset: v1
          weight: 100
        - destination:
            host: frontend.demo-app.svc.cluster.local
            subset: v2
          weight: 0
