apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../versions/v1
  - ../../versions/v2
  - pdbs.yaml
patches:
  - path: payment-mock-v2-fault.yaml
  - path: deployment-ha-patch.yaml
