apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: demo-ops
spec:
  limits:
    - type: Container
      default:
        cpu: 300m
        memory: 384Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: demo-ops-quota
  namespace: demo-ops
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "20"