apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gitrepository.yaml
  - kustomization-platform.yaml
  - kustomization-apps.yaml
  - kustomization-image-automation.yaml
  - kustomization-mesh.yaml
  - kustomization-ops-loadgen.yaml
