apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-ops-role
  namespace: demo-app
rules:
  - apiGroups: ["", "apps", "networking.istio.io"]
    resources: ["pods", "services", "endpoints", "configmaps", "deployments", "events", "virtualservices", "destinationrules"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]