apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend
  namespace: demo-app
spec:
  hosts:
    - frontend.demo-app.svc.cluster.local
  http:
    - route:
        - destination:
            host: frontend.demo-app.svc.cluster.local
            subset: v1
          weight: 100
        - destination:
            host: frontend.demo-app.svc.cluster.local
            subset: v2
          weight: 0