apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: payment-mock
  namespace: demo-app
spec:
  hosts:
    - payment-mock.demo-app.svc.cluster.local
  http:
    - name: from-checkout-v2
      match:
        - sourceLabels:
            app: checkout-api
            version: v2
      route:
        - destination:
            host: payment-mock.demo-app.svc.cluster.local
            subset: v2
          weight: 100
    - name: from-checkout-v1
      match:
        - sourceLabels:
            app: checkout-api
            version: v1
      route:
        - destination:
            host: payment-mock.demo-app.svc.cluster.local
            subset: v1
          weight: 100
    - name: default
      route:
        - destination:
            host: payment-mock.demo-app.svc.cluster.local
            subset: v1
          weight: 100
        - destination:
            host: payment-mock.demo-app.svc.cluster.local
            subset: v2
          weight: 0
