apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../virtualservice
patches:
  - path: weights.yaml
  - path: weights-catalog-api.yaml
  - path: weights-checkout-api.yaml
  - path: weights-payment-mock.yaml
  - path: weights-ingress.yaml
