apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: otel-shop-frontend
  namespace: flux-system
spec:
  image: ghcr.io/your-org/otel-shop-lite-frontend
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: otel-shop-catalog-api
  namespace: flux-system
spec:
  image: ghcr.io/your-org/otel-shop-lite-catalog-api
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: otel-shop-checkout-api
  namespace: flux-system
spec:
  image: ghcr.io/your-org/otel-shop-lite-checkout-api
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: otel-shop-payment-mock
  namespace: flux-system
spec:
  image: ghcr.io/your-org/otel-shop-lite-payment-mock
  interval: 1m0s